// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: test_service/service.proto

package server

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConcStringsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstStr  string `protobuf:"bytes,1,opt,name=firstStr,proto3" json:"firstStr,omitempty"`
	SecondStr string `protobuf:"bytes,2,opt,name=secondStr,proto3" json:"secondStr,omitempty"`
}

func (x *ConcStringsRequest) Reset() {
	*x = ConcStringsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_service_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConcStringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcStringsRequest) ProtoMessage() {}

func (x *ConcStringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcStringsRequest.ProtoReflect.Descriptor instead.
func (*ConcStringsRequest) Descriptor() ([]byte, []int) {
	return file_test_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConcStringsRequest) GetFirstStr() string {
	if x != nil {
		return x.FirstStr
	}
	return ""
}

func (x *ConcStringsRequest) GetSecondStr() string {
	if x != nil {
		return x.SecondStr
	}
	return ""
}

type ConcStringsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ConcStringsResponse) Reset() {
	*x = ConcStringsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_service_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConcStringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcStringsResponse) ProtoMessage() {}

func (x *ConcStringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcStringsResponse.ProtoReflect.Descriptor instead.
func (*ConcStringsResponse) Descriptor() ([]byte, []int) {
	return file_test_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConcStringsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_test_service_service_proto protoreflect.FileDescriptor

var file_test_service_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x65,
	0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x63,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x53, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x53, 0x74, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x22, 0x2d, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x63,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x76, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x63, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x20, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0d, 0x22, 0x08, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x3a, 0x01, 0x2a, 0x42,
	0x19, 0x5a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_test_service_service_proto_rawDescOnce sync.Once
	file_test_service_service_proto_rawDescData = file_test_service_service_proto_rawDesc
)

func file_test_service_service_proto_rawDescGZIP() []byte {
	file_test_service_service_proto_rawDescOnce.Do(func() {
		file_test_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_service_service_proto_rawDescData)
	})
	return file_test_service_service_proto_rawDescData
}

var file_test_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_service_service_proto_goTypes = []interface{}{
	(*ConcStringsRequest)(nil),  // 0: test_service.ConcStringsRequest
	(*ConcStringsResponse)(nil), // 1: test_service.ConcStringsResponse
}
var file_test_service_service_proto_depIdxs = []int32{
	0, // 0: test_service.TestService.ConcStrings:input_type -> test_service.ConcStringsRequest
	1, // 1: test_service.TestService.ConcStrings:output_type -> test_service.ConcStringsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_service_service_proto_init() }
func file_test_service_service_proto_init() {
	if File_test_service_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_service_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConcStringsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_service_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConcStringsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_service_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_service_service_proto_goTypes,
		DependencyIndexes: file_test_service_service_proto_depIdxs,
		MessageInfos:      file_test_service_service_proto_msgTypes,
	}.Build()
	File_test_service_service_proto = out.File
	file_test_service_service_proto_rawDesc = nil
	file_test_service_service_proto_goTypes = nil
	file_test_service_service_proto_depIdxs = nil
}
