version: "3.5"

services:
  proxy:
    build:
      context: ../
      dockerfile: compose/Dockerfile_proxy
    ports:
      - "8081:8081"
    volumes:
      - ../:/go/src/proxy
    command: [ "go", "run", "/go/src/proxy/cmd/proxy/main.go" ]

  service:
    build:
      context: ../
      dockerfile: compose/Dockerfile_service
    volumes:
      - ../:/go/src/service
    command: ["go", "run", "/go/src/service/cmd/test_service/main.go"]